### ISSUE TITLE
String pattern not work

### ISSUE THREAD

**Issue by bigYellowDuck** [jdesgats/ljsonschema#9]
Hi， ljsonschma doesn't work expected when I try the regular expressions: [regular expressions](https://json-schema.org/understanding-json-schema/reference/regular_expressions.html#regular-expressions).

The error message is: property "OpenKey" validation failed: failed to match pattern "^(\\([0-9]{3}\\))?[0-9]{3}-[0-9]{4}$" with "555-1212"

**Comment by bigYellowDuck** [comment]
I am wondering how match_pattern function behave like the documents.

**Comment by jdesgats** [comment]
As stated in the readme document, the pattern matching feature relies by default on `string.find`, which doesn't implement the ECMA-262 regular expressions required by JSON schema. In particular, `string.find` doesn't understand repetitions or optional groups that use used in your example.

As you noted, you can provide your own function by passing it as the `match_pattern` field in the option table when instantiating the schema. The function must behave like `string.find`:

* It gets the string to match and then the pattern as arguments
* It must return something that evaluates to true if there's a match, otherwise `false` (or `nil`)

I guess you can use one of the many PCRE bindings available for Lua for your use case.

See https://github.com/jdesgats/ljsonschema/blob/master/jsonschema/init.lua#L661
